// 页面初始化使用
export const UPDATE_PAGE_INFO = "UPDATE_PAGE_INFO"
export const UPDATE_PAGE_SS_INFO = "UPDATE_PAGE_SS_INFO"
export const UPDATE_PAGE_ACCESS_TOKEN = "UPDATE_PAGE_ACCESS_TOKEN"

export const UPDATE_USER_INFO = "UPDATE_USER_INFO"
